package load

import "dwarf-sweeper/pkg/sfx"

func SFX() {
	sfx.SoundPlayer.RegisterSound("assets/sound/bite.wav", "bite")
	sfx.SoundPlayer.RegisterSound("assets/sound/bigblast1.wav", "bigblast1")
	sfx.SoundPlayer.RegisterSound("assets/sound/bigbombdefuse.wav", "bigbombdefuse")
	sfx.SoundPlayer.RegisterSound("assets/sound/bigbombsmash.wav", "bigbombsmash")
	sfx.SoundPlayer.RegisterSound("assets/sound/click.wav", "click")
	sfx.SoundPlayer.RegisterSound("assets/sound/clink.wav", "clink")
	sfx.SoundPlayer.RegisterSound("assets/sound/doubleblast.wav", "doubleblast")
	sfx.SoundPlayer.RegisterSound("assets/sound/emerge.wav", "emerge")
	sfx.SoundPlayer.RegisterSound("assets/sound/fuselong.wav", "fuselong")
	sfx.SoundPlayer.RegisterSound("assets/sound/fuseshort.wav", "fuseshort")
	sfx.SoundPlayer.RegisterSound("assets/sound/gnomestep.wav", "gnomestep")
	//sfx.SoundPlayer.RegisterSound("assets/sound/impact1.wav", "impact1")
	//sfx.SoundPlayer.RegisterSound("assets/sound/impact2.wav", "impact2")
	//sfx.SoundPlayer.RegisterSound("assets/sound/impact3.wav", "impact3")
	//sfx.SoundPlayer.RegisterSound("assets/sound/impact4.wav", "impact4")
	sfx.SoundPlayer.RegisterSound("assets/sound/mpcorrect.wav", "mpcorrect")
	sfx.SoundPlayer.RegisterSound("assets/sound/mpwrong.wav", "mpwrong")
	sfx.SoundPlayer.RegisterSound("assets/sound/roar.wav", "roar")
	sfx.SoundPlayer.RegisterSound("assets/sound/rocks1.wav", "rocks1")
	sfx.SoundPlayer.RegisterSound("assets/sound/rocks2.wav", "rocks2")
	sfx.SoundPlayer.RegisterSound("assets/sound/rocks3.wav", "rocks3")
	sfx.SoundPlayer.RegisterSound("assets/sound/rocks4.wav", "rocks4")
	sfx.SoundPlayer.RegisterSound("assets/sound/rocks5.wav", "rocks5")
	sfx.SoundPlayer.RegisterSound("assets/sound/rockslide.wav", "rockslide")
	sfx.SoundPlayer.RegisterSound("assets/sound/shovel.wav", "shovel")
	sfx.SoundPlayer.RegisterSound("assets/sound/sludge1.wav", "sludge1")
	sfx.SoundPlayer.RegisterSound("assets/sound/sludge2.wav", "sludge2")
	sfx.SoundPlayer.RegisterSound("assets/sound/sludge3.wav", "sludge3")
	sfx.SoundPlayer.RegisterSound("assets/sound/sludge4.wav", "sludge4")
	sfx.SoundPlayer.RegisterSound("assets/sound/splat.wav", "splat")
	sfx.SoundPlayer.RegisterSound("assets/sound/squeak1.wav", "squeak1")
	sfx.SoundPlayer.RegisterSound("assets/sound/squeak2.wav", "squeak2")
	sfx.SoundPlayer.RegisterSound("assets/sound/squeak3.wav", "squeak3")
	sfx.SoundPlayer.RegisterSound("assets/sound/squeak4.wav", "squeak4")
	sfx.SoundPlayer.RegisterSound("assets/sound/squeak5.wav", "squeak5")
	sfx.SoundPlayer.RegisterSound("assets/sound/step1.wav", "step1")
	sfx.SoundPlayer.RegisterSound("assets/sound/step2.wav", "step2")
	sfx.SoundPlayer.RegisterSound("assets/sound/step3.wav", "step3")
	sfx.SoundPlayer.RegisterSound("assets/sound/step4.wav", "step4")
	sfx.SoundPlayer.RegisterSound("assets/sound/wingflap.wav", "wingflap")
}
