package load

import (
	"dwarf-sweeper/internal/constants"
	"dwarf-sweeper/pkg/img"
	"dwarf-sweeper/pkg/typeface"
)

func Symbols() {
	// keyboard
	typeface.RegisterSymbol("Space", img.Batchers[constants.MenuSprites].GetSprite("Space"), 1.0)
	typeface.RegisterSymbol("Apostrophe", img.Batchers[constants.MenuSprites].GetSprite("Apostrophe"), 1.0)
	typeface.RegisterSymbol("Comma", img.Batchers[constants.MenuSprites].GetSprite("Comma"), 1.0)
	typeface.RegisterSymbol("Minus", img.Batchers[constants.MenuSprites].GetSprite("Minus"), 1.0)
	typeface.RegisterSymbol("Period", img.Batchers[constants.MenuSprites].GetSprite("Period"), 1.0)
	typeface.RegisterSymbol("Slash", img.Batchers[constants.MenuSprites].GetSprite("Slash"), 1.0)
	typeface.RegisterSymbol("0", img.Batchers[constants.MenuSprites].GetSprite("0"), 1.0)
	typeface.RegisterSymbol("1", img.Batchers[constants.MenuSprites].GetSprite("1"), 1.0)
	typeface.RegisterSymbol("2", img.Batchers[constants.MenuSprites].GetSprite("2"), 1.0)
	typeface.RegisterSymbol("3", img.Batchers[constants.MenuSprites].GetSprite("3"), 1.0)
	typeface.RegisterSymbol("4", img.Batchers[constants.MenuSprites].GetSprite("4"), 1.0)
	typeface.RegisterSymbol("5", img.Batchers[constants.MenuSprites].GetSprite("5"), 1.0)
	typeface.RegisterSymbol("6", img.Batchers[constants.MenuSprites].GetSprite("6"), 1.0)
	typeface.RegisterSymbol("7", img.Batchers[constants.MenuSprites].GetSprite("7"), 1.0)
	typeface.RegisterSymbol("8", img.Batchers[constants.MenuSprites].GetSprite("8"), 1.0)
	typeface.RegisterSymbol("9", img.Batchers[constants.MenuSprites].GetSprite("9"), 1.0)
	typeface.RegisterSymbol("Semicolon", img.Batchers[constants.MenuSprites].GetSprite("Semicolon"), 1.0)
	typeface.RegisterSymbol("Equal", img.Batchers[constants.MenuSprites].GetSprite("Equal"), 1.0)
	typeface.RegisterSymbol("A", img.Batchers[constants.MenuSprites].GetSprite("A"), 1.0)
	typeface.RegisterSymbol("B", img.Batchers[constants.MenuSprites].GetSprite("B"), 1.0)
	typeface.RegisterSymbol("C", img.Batchers[constants.MenuSprites].GetSprite("C"), 1.0)
	typeface.RegisterSymbol("D", img.Batchers[constants.MenuSprites].GetSprite("D"), 1.0)
	typeface.RegisterSymbol("E", img.Batchers[constants.MenuSprites].GetSprite("E"), 1.0)
	typeface.RegisterSymbol("F", img.Batchers[constants.MenuSprites].GetSprite("F"), 1.0)
	typeface.RegisterSymbol("G", img.Batchers[constants.MenuSprites].GetSprite("G"), 1.0)
	typeface.RegisterSymbol("H", img.Batchers[constants.MenuSprites].GetSprite("H"), 1.0)
	typeface.RegisterSymbol("I", img.Batchers[constants.MenuSprites].GetSprite("I"), 1.0)
	typeface.RegisterSymbol("J", img.Batchers[constants.MenuSprites].GetSprite("J"), 1.0)
	typeface.RegisterSymbol("K", img.Batchers[constants.MenuSprites].GetSprite("K"), 1.0)
	typeface.RegisterSymbol("L", img.Batchers[constants.MenuSprites].GetSprite("L"), 1.0)
	typeface.RegisterSymbol("M", img.Batchers[constants.MenuSprites].GetSprite("M"), 1.0)
	typeface.RegisterSymbol("N", img.Batchers[constants.MenuSprites].GetSprite("N"), 1.0)
	typeface.RegisterSymbol("O", img.Batchers[constants.MenuSprites].GetSprite("O"), 1.0)
	typeface.RegisterSymbol("P", img.Batchers[constants.MenuSprites].GetSprite("P"), 1.0)
	typeface.RegisterSymbol("Q", img.Batchers[constants.MenuSprites].GetSprite("Q"), 1.0)
	typeface.RegisterSymbol("R", img.Batchers[constants.MenuSprites].GetSprite("R"), 1.0)
	typeface.RegisterSymbol("S", img.Batchers[constants.MenuSprites].GetSprite("S"), 1.0)
	typeface.RegisterSymbol("T", img.Batchers[constants.MenuSprites].GetSprite("T"), 1.0)
	typeface.RegisterSymbol("U", img.Batchers[constants.MenuSprites].GetSprite("U"), 1.0)
	typeface.RegisterSymbol("V", img.Batchers[constants.MenuSprites].GetSprite("V"), 1.0)
	typeface.RegisterSymbol("W", img.Batchers[constants.MenuSprites].GetSprite("W"), 1.0)
	typeface.RegisterSymbol("X", img.Batchers[constants.MenuSprites].GetSprite("X"), 1.0)
	typeface.RegisterSymbol("Y", img.Batchers[constants.MenuSprites].GetSprite("Y"), 1.0)
	typeface.RegisterSymbol("Z", img.Batchers[constants.MenuSprites].GetSprite("Z"), 1.0)
	typeface.RegisterSymbol("LeftBracket", img.Batchers[constants.MenuSprites].GetSprite("LeftBracket"), 1.0)
	typeface.RegisterSymbol("Backslash", img.Batchers[constants.MenuSprites].GetSprite("Backslash"), 1.0)
	typeface.RegisterSymbol("RightBracket", img.Batchers[constants.MenuSprites].GetSprite("RightBracket"), 1.0)
	typeface.RegisterSymbol("GraveAccent", img.Batchers[constants.MenuSprites].GetSprite("GraveAccent"), 1.0)
	typeface.RegisterSymbol("World1", img.Batchers[constants.MenuSprites].GetSprite("World1"), 1.0)
	typeface.RegisterSymbol("World2", img.Batchers[constants.MenuSprites].GetSprite("World2"), 1.0)
	typeface.RegisterSymbol("Escape", img.Batchers[constants.MenuSprites].GetSprite("Escape"), 1.0)
	typeface.RegisterSymbol("Enter", img.Batchers[constants.MenuSprites].GetSprite("Enter"), 1.0)
	typeface.RegisterSymbol("Tab", img.Batchers[constants.MenuSprites].GetSprite("Tab"), 1.0)
	typeface.RegisterSymbol("Backspace", img.Batchers[constants.MenuSprites].GetSprite("Backspace"), 1.0)
	typeface.RegisterSymbol("Insert", img.Batchers[constants.MenuSprites].GetSprite("Insert"), 1.0)
	typeface.RegisterSymbol("Delete", img.Batchers[constants.MenuSprites].GetSprite("Delete"), 1.0)
	typeface.RegisterSymbol("Right", img.Batchers[constants.MenuSprites].GetSprite("Right"), 1.0)
	typeface.RegisterSymbol("Left", img.Batchers[constants.MenuSprites].GetSprite("Left"), 1.0)
	typeface.RegisterSymbol("Down", img.Batchers[constants.MenuSprites].GetSprite("Down"), 1.0)
	typeface.RegisterSymbol("Up", img.Batchers[constants.MenuSprites].GetSprite("Up"), 1.0)
	typeface.RegisterSymbol("PageUp", img.Batchers[constants.MenuSprites].GetSprite("PageUp"), 1.0)
	typeface.RegisterSymbol("PageDown", img.Batchers[constants.MenuSprites].GetSprite("PageDown"), 1.0)
	typeface.RegisterSymbol("Home", img.Batchers[constants.MenuSprites].GetSprite("Home"), 1.0)
	typeface.RegisterSymbol("End", img.Batchers[constants.MenuSprites].GetSprite("End"), 1.0)
	typeface.RegisterSymbol("CapsLock", img.Batchers[constants.MenuSprites].GetSprite("CapsLock"), 1.0)
	typeface.RegisterSymbol("ScrollLock", img.Batchers[constants.MenuSprites].GetSprite("ScrollLock"), 1.0)
	typeface.RegisterSymbol("NumLock", img.Batchers[constants.MenuSprites].GetSprite("NumLock"), 1.0)
	typeface.RegisterSymbol("PrintScreen", img.Batchers[constants.MenuSprites].GetSprite("PrintScreen"), 1.0)
	typeface.RegisterSymbol("Pause", img.Batchers[constants.MenuSprites].GetSprite("Pause"), 1.0)
	typeface.RegisterSymbol("F1", img.Batchers[constants.MenuSprites].GetSprite("F1"), 1.0)
	typeface.RegisterSymbol("F2", img.Batchers[constants.MenuSprites].GetSprite("F2"), 1.0)
	typeface.RegisterSymbol("F3", img.Batchers[constants.MenuSprites].GetSprite("F3"), 1.0)
	typeface.RegisterSymbol("F4", img.Batchers[constants.MenuSprites].GetSprite("F4"), 1.0)
	typeface.RegisterSymbol("F5", img.Batchers[constants.MenuSprites].GetSprite("F5"), 1.0)
	typeface.RegisterSymbol("F6", img.Batchers[constants.MenuSprites].GetSprite("F6"), 1.0)
	typeface.RegisterSymbol("F7", img.Batchers[constants.MenuSprites].GetSprite("F7"), 1.0)
	typeface.RegisterSymbol("F8", img.Batchers[constants.MenuSprites].GetSprite("F8"), 1.0)
	typeface.RegisterSymbol("F9", img.Batchers[constants.MenuSprites].GetSprite("F9"), 1.0)
	typeface.RegisterSymbol("F10", img.Batchers[constants.MenuSprites].GetSprite("F10"), 1.0)
	typeface.RegisterSymbol("F11", img.Batchers[constants.MenuSprites].GetSprite("F11"), 1.0)
	typeface.RegisterSymbol("F12", img.Batchers[constants.MenuSprites].GetSprite("F12"), 1.0)
	typeface.RegisterSymbol("F13", img.Batchers[constants.MenuSprites].GetSprite("F13"), 1.0)
	typeface.RegisterSymbol("F14", img.Batchers[constants.MenuSprites].GetSprite("F14"), 1.0)
	typeface.RegisterSymbol("F15", img.Batchers[constants.MenuSprites].GetSprite("F15"), 1.0)
	typeface.RegisterSymbol("F16", img.Batchers[constants.MenuSprites].GetSprite("F16"), 1.0)
	typeface.RegisterSymbol("F17", img.Batchers[constants.MenuSprites].GetSprite("F17"), 1.0)
	typeface.RegisterSymbol("F18", img.Batchers[constants.MenuSprites].GetSprite("F18"), 1.0)
	typeface.RegisterSymbol("F19", img.Batchers[constants.MenuSprites].GetSprite("F19"), 1.0)
	typeface.RegisterSymbol("F20", img.Batchers[constants.MenuSprites].GetSprite("F20"), 1.0)
	typeface.RegisterSymbol("F21", img.Batchers[constants.MenuSprites].GetSprite("F21"), 1.0)
	typeface.RegisterSymbol("F22", img.Batchers[constants.MenuSprites].GetSprite("F22"), 1.0)
	typeface.RegisterSymbol("F23", img.Batchers[constants.MenuSprites].GetSprite("F23"), 1.0)
	typeface.RegisterSymbol("F24", img.Batchers[constants.MenuSprites].GetSprite("F24"), 1.0)
	typeface.RegisterSymbol("F25", img.Batchers[constants.MenuSprites].GetSprite("F25"), 1.0)
	typeface.RegisterSymbol("KP0", img.Batchers[constants.MenuSprites].GetSprite("KP0"), 1.0)
	typeface.RegisterSymbol("KP1", img.Batchers[constants.MenuSprites].GetSprite("KP1"), 1.0)
	typeface.RegisterSymbol("KP2", img.Batchers[constants.MenuSprites].GetSprite("KP2"), 1.0)
	typeface.RegisterSymbol("KP3", img.Batchers[constants.MenuSprites].GetSprite("KP3"), 1.0)
	typeface.RegisterSymbol("KP4", img.Batchers[constants.MenuSprites].GetSprite("KP4"), 1.0)
	typeface.RegisterSymbol("KP5", img.Batchers[constants.MenuSprites].GetSprite("KP5"), 1.0)
	typeface.RegisterSymbol("KP6", img.Batchers[constants.MenuSprites].GetSprite("KP6"), 1.0)
	typeface.RegisterSymbol("KP7", img.Batchers[constants.MenuSprites].GetSprite("KP7"), 1.0)
	typeface.RegisterSymbol("KP8", img.Batchers[constants.MenuSprites].GetSprite("KP8"), 1.0)
	typeface.RegisterSymbol("KP9", img.Batchers[constants.MenuSprites].GetSprite("KP9"), 1.0)
	typeface.RegisterSymbol("KPDecimal", img.Batchers[constants.MenuSprites].GetSprite("KPDecimal"), 1.0)
	typeface.RegisterSymbol("KPDivide", img.Batchers[constants.MenuSprites].GetSprite("KPDivide"), 1.0)
	typeface.RegisterSymbol("KPMultiply", img.Batchers[constants.MenuSprites].GetSprite("KPMultiply"), 1.0)
	typeface.RegisterSymbol("KPSubtract", img.Batchers[constants.MenuSprites].GetSprite("KPSubtract"), 1.0)
	typeface.RegisterSymbol("KPAdd", img.Batchers[constants.MenuSprites].GetSprite("KPAdd"), 1.0)
	typeface.RegisterSymbol("KPEnter", img.Batchers[constants.MenuSprites].GetSprite("KPEnter"), 1.0)
	typeface.RegisterSymbol("KPEqual", img.Batchers[constants.MenuSprites].GetSprite("KPEqual"), 1.0)
	typeface.RegisterSymbol("LeftShift", img.Batchers[constants.MenuSprites].GetSprite("LeftShift"), 1.0)
	typeface.RegisterSymbol("LeftControl", img.Batchers[constants.MenuSprites].GetSprite("LeftControl"), 1.0)
	typeface.RegisterSymbol("LeftAlt", img.Batchers[constants.MenuSprites].GetSprite("LeftAlt"), 1.0)
	typeface.RegisterSymbol("LeftSuper", img.Batchers[constants.MenuSprites].GetSprite("LeftSuper"), 1.0)
	typeface.RegisterSymbol("RightShift", img.Batchers[constants.MenuSprites].GetSprite("RightShift"), 1.0)
	typeface.RegisterSymbol("RightControl", img.Batchers[constants.MenuSprites].GetSprite("RightControl"), 1.0)
	typeface.RegisterSymbol("RightAlt", img.Batchers[constants.MenuSprites].GetSprite("RightAlt"), 1.0)
	typeface.RegisterSymbol("RightSuper", img.Batchers[constants.MenuSprites].GetSprite("RightSuper"), 1.0)
	typeface.RegisterSymbol("Menu", img.Batchers[constants.MenuSprites].GetSprite("Menu"), 1.0)

	// mouse
	typeface.RegisterSymbol("MouseButton1", img.Batchers[constants.MenuSprites].GetSprite("MouseButton1"), 1.0)
	typeface.RegisterSymbol("MouseButton2", img.Batchers[constants.MenuSprites].GetSprite("MouseButton2"), 1.0)
	typeface.RegisterSymbol("MouseButton3", img.Batchers[constants.MenuSprites].GetSprite("MouseButton3"), 1.0)
	typeface.RegisterSymbol("MouseButton4", img.Batchers[constants.MenuSprites].GetSprite("MouseButton4"), 1.0)
	typeface.RegisterSymbol("MouseButton5", img.Batchers[constants.MenuSprites].GetSprite("MouseButton5"), 1.0)
	typeface.RegisterSymbol("MouseButton6", img.Batchers[constants.MenuSprites].GetSprite("MouseButton6"), 1.0)
	typeface.RegisterSymbol("MouseButton7", img.Batchers[constants.MenuSprites].GetSprite("MouseButton7"), 1.0)
	typeface.RegisterSymbol("MouseButton8", img.Batchers[constants.MenuSprites].GetSprite("MouseButton8"), 1.0)
	typeface.RegisterSymbol("MouseButtonLast", img.Batchers[constants.MenuSprites].GetSprite("MouseButtonLast"), 1.0)
	typeface.RegisterSymbol("MouseButtonLeft", img.Batchers[constants.MenuSprites].GetSprite("MouseButtonLeft"), 1.0)
	typeface.RegisterSymbol("MouseButtonRight", img.Batchers[constants.MenuSprites].GetSprite("MouseButtonRight"), 1.0)
	typeface.RegisterSymbol("MouseButtonMiddle", img.Batchers[constants.MenuSprites].GetSprite("MouseButtonMiddle"), 1.0)
	typeface.RegisterSymbol("MouseScrollUp", img.Batchers[constants.MenuSprites].GetSprite("MouseScrollUp"), 1.)
	typeface.RegisterSymbol("MouseScrollDown", img.Batchers[constants.MenuSprites].GetSprite("MouseScrollDown"), 1.)

	// gamepad
	typeface.RegisterSymbol("ButtonA", img.Batchers[constants.MenuSprites].GetSprite("ButtonA"), 1.)
	typeface.RegisterSymbol("ButtonB", img.Batchers[constants.MenuSprites].GetSprite("ButtonB"), 1.)
	typeface.RegisterSymbol("ButtonX", img.Batchers[constants.MenuSprites].GetSprite("ButtonX"), 1.)
	typeface.RegisterSymbol("ButtonY", img.Batchers[constants.MenuSprites].GetSprite("ButtonY"), 1.)
	typeface.RegisterSymbol("ButtonLeftBumper", img.Batchers[constants.MenuSprites].GetSprite("ButtonLeftBumper"), 1.)
	typeface.RegisterSymbol("ButtonRightBumper", img.Batchers[constants.MenuSprites].GetSprite("ButtonRightBumper"), 1.)
	typeface.RegisterSymbol("ButtonBack", img.Batchers[constants.MenuSprites].GetSprite("ButtonBack"), 1.)
	typeface.RegisterSymbol("ButtonStart", img.Batchers[constants.MenuSprites].GetSprite("ButtonStart"), 1.)
	typeface.RegisterSymbol("ButtonGuide", img.Batchers[constants.MenuSprites].GetSprite("ButtonGuide"), 1.)
	typeface.RegisterSymbol("ButtonLeftThumb", img.Batchers[constants.MenuSprites].GetSprite("ButtonLeftThumb"), 1.)
	typeface.RegisterSymbol("ButtonRightThumb", img.Batchers[constants.MenuSprites].GetSprite("ButtonRightThumb"), 1.)
	typeface.RegisterSymbol("ButtonDpadUp", img.Batchers[constants.MenuSprites].GetSprite("ButtonDpadUp"), 1.)
	typeface.RegisterSymbol("ButtonDpadRight", img.Batchers[constants.MenuSprites].GetSprite("ButtonDpadRight"), 1.)
	typeface.RegisterSymbol("ButtonDpadDown", img.Batchers[constants.MenuSprites].GetSprite("ButtonDpadDown"), 1.)
	typeface.RegisterSymbol("ButtonDpadLeft", img.Batchers[constants.MenuSprites].GetSprite("ButtonDpadLeft"), 1.)
	typeface.RegisterSymbol("ButtonLast", img.Batchers[constants.MenuSprites].GetSprite("ButtonLast"), 1.)
	typeface.RegisterSymbol("ButtonCross", img.Batchers[constants.MenuSprites].GetSprite("ButtonCross"), 1.)
	typeface.RegisterSymbol("ButtonCircle", img.Batchers[constants.MenuSprites].GetSprite("ButtonCircle"), 1.)
	typeface.RegisterSymbol("ButtonSquare", img.Batchers[constants.MenuSprites].GetSprite("ButtonSquare"), 1.)
	typeface.RegisterSymbol("ButtonTriangle", img.Batchers[constants.MenuSprites].GetSprite("ButtonTriangle"), 1.)

	// gamepad axes
	typeface.RegisterSymbol("AxisLeftX", img.Batchers[constants.MenuSprites].GetSprite("AxisLeftX"), 1.)
	typeface.RegisterSymbol("AxisLeftY", img.Batchers[constants.MenuSprites].GetSprite("AxisLeftY"), 1.)
	typeface.RegisterSymbol("AxisRightX", img.Batchers[constants.MenuSprites].GetSprite("AxisRightX"), 1.)
	typeface.RegisterSymbol("AxisRightY", img.Batchers[constants.MenuSprites].GetSprite("AxisRightY"), 1.)
	typeface.RegisterSymbol("AxisLeftXPos", img.Batchers[constants.MenuSprites].GetSprite("AxisLeftXPos"), 1.)
	typeface.RegisterSymbol("AxisLeftXNeg", img.Batchers[constants.MenuSprites].GetSprite("AxisLeftXNeg"), 1.)
	typeface.RegisterSymbol("AxisLeftYPos", img.Batchers[constants.MenuSprites].GetSprite("AxisLeftYPos"), 1.)
	typeface.RegisterSymbol("AxisLeftYNeg", img.Batchers[constants.MenuSprites].GetSprite("AxisLeftYNeg"), 1.)
	typeface.RegisterSymbol("AxisRightXPos", img.Batchers[constants.MenuSprites].GetSprite("AxisRightXPos"), 1.)
	typeface.RegisterSymbol("AxisRightXNeg", img.Batchers[constants.MenuSprites].GetSprite("AxisRightXNeg"), 1.)
	typeface.RegisterSymbol("AxisRightYPos", img.Batchers[constants.MenuSprites].GetSprite("AxisRightYPos"), 1.)
	typeface.RegisterSymbol("AxisRightYNeg", img.Batchers[constants.MenuSprites].GetSprite("AxisRightYNeg"), 1.)
	typeface.RegisterSymbol("AxisLeftTrigger", img.Batchers[constants.MenuSprites].GetSprite("AxisLeftTrigger"), 1.)
	typeface.RegisterSymbol("AxisRightTrigger", img.Batchers[constants.MenuSprites].GetSprite("AxisRightTrigger"), 1.)

	// puzzles
	typeface.RegisterSymbol("check", img.Batchers[constants.PuzzleKey].GetAnimation("check").S[0], 1.)
	typeface.RegisterSymbol("mine", img.Batchers[constants.PuzzleKey].GetSprite("mine"), 1.)
	typeface.RegisterSymbol("leave", img.Batchers[constants.PuzzleKey].GetSprite("leave"), 1.)
	typeface.RegisterSymbol("help", img.Batchers[constants.PuzzleKey].GetSprite("help"), 1.)

	// other
	typeface.RegisterSymbol("checkmark", img.Batchers[constants.MenuSprites].GetSprite("checkmark"), 1.)
}